Repository buidl-labs/YieldScan, pull requests merged in 2020-05, with the labels that each got.

#15 Suggested Validators UI - View
  public/LogoYS.svg
  src/App.jsx
  src/components/CustomButton.js
  src/components/NavBar.jsx
  src/components/SuggestedValidators/ExpectedReturns.js
  src/components/SuggestedValidators/SuggestedValidators.js
  src/components/SuggestedValidators/ValidatorTile.js
  src/components/nominator_components/NominatorApp.jsx
  src/components/nominator_components/Rectangleandlines.jsx
  src/components/validator_components/ValidatorApp.jsx
  src/index.js
  src/stylesheets/scss/index.scss
Labels: ui-ux

#18 UI for Wallet Connect View
  public/MoneybagGraphic.svg
  src/App.jsx
  src/components/SuggestedValidators/ValidatorTile.js
  src/components/WalletConnect/WalletConnect.js
  src/constants.js
Labels: ui-ux

#21 UI for Confirmation Page
  src/App.jsx
  src/components/ConfirmationPage/ConfirmationPage.js
  src/components/CustomButton.js
  src/components/SuggestedValidators/SuggestedValidators.js
  src/components/SuggestedValidators/ValidatorTile.js
  src/components/WalletConnect/WalletConnect.js
  src/constants.js
Labels: ui-ux

#39 Bugfix/returns calculation
  src/components/EditValidators/EditValidators.js
  src/components/NetworkDetails/ValidatorsTable.js
  src/components/ReturnsCalculator.jsx
  src/components/SuggestedValidators/SuggestedValidators.js
  src/components/SuggestedValidators/ValidatorTile.js
  src/components/SuggestedValidators/suggestions.js
  src/getValidatorInfo.js
Labels: bug

#51 Hotfix/tx status
  public/index.html
  src/App.jsx
  src/components/ConfirmationPage/ConfirmationPage.js
  src/components/ConfirmationPage/TxStatus.js
  src/components/EditValidators/Table.js
  src/components/NetworkDetails/NetworkDetails.js
  src/components/NetworkDetails/NominatorsTable.js
  src/components/NetworkDetails/ValidatorsTable.js
  src/components/ReturnsCalculator.jsx
  src/components/Testing/index.js
  src/getNominatorInfo.js
  src/getValidatorInfo.js
Labels: +P1, ui-ux
